plugins:
  # GitLab support
  - '@semantic-release/gitlab'
  # analyses the Git commits
  - '@semantic-release/commit-analyzer'
  # generates the release note from the Git commit messages
  - '@semantic-release/release-notes-generator'
  # generates the CHANGELOG.md file
  - '@semantic-release/changelog'
  - - semantic-release-replace-plugin
    - replacements:
        - files:
            - 'VERSION.ini'
          from:
            - ^version *= *"\d+\.\d+\.\d+"
          to:
            - 'version = "${nextRelease.version}"'
          countMatches: true

  # git commit/push modified files
  - - '@semantic-release/git'
    - assets:
        - 'CHANGELOG.md'
        - 'VERSION.ini'
      # the commit MUST trigger a pipeline on tag (to perform publish jobs)
      # can be skipped on prod branch
      message: 'chore(release): ${nextRelease.version} [skip ci]'
branches:
  - main
  - master
  - name: feat/*
    prerelease: false
  - name: fix/*
    prerelease: false
  - name: hotfix/*
    prerelease: false
  - name: release/*
    prerelease: false
tagFormat: '${version}'
